### ISSUE TITLE
Mysql not starting

### ISSUE THREAD

**Issue by prasenforu** [fabric8io/kubernetes-zipkin#107]
Environment : OCP 3.3
OS: RHEL 7.3

Following http://repo1.maven.org/maven2/io/fabric8/zipkin/zipkin-starter/0.1.5/zipkin-starter-0.1.5-openshift.yml

Looks like I can use any one storage mysql, cassandra or kafka so based on that remove all others except mysql from above yml file additionally removed persistent volume also instead of using hostpath & finally
my yml comes as follow.

```
---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/prometheus"
      prometheus.io/port: "9411"
      fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/git-branch: "release-v0.1.5"
      fabric8.io/build-id: "3"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
    labels:
      provider: "fabric8"
      project: "zipkin"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin"
  spec:
    ports:
    - port: 9411
      protocol: "TCP"
      targetPort: 9411
    selector:
      project: "zipkin"
      provider: "fabric8"
      group: "io.fabric8.zipkin"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/git-branch: "release-v0.1.5"
      fabric8.io/build-id: "3"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
    labels:
      provider: "fabric8"
      project: "zipkin-mysql"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin-mysql"
  spec:
    ports:
    - port: 3306
      protocol: "TCP"
      targetPort: 3306
    selector:
      project: "zipkin-mysql"
      provider: "fabric8"
      group: "io.fabric8.zipkin"

- apiVersion: "v1"
  kind: "ConfigMap"
  metadata:
    labels:
      provider: "fabric8"
      project: "zipkin-mysql"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin-mysql-cnf"
  data:
    custom.cnf: "[mysqld]\nsql-mode=\"\"\n"
- apiVersion: "v1"
  kind: "ConfigMap"
  metadata:
    labels:
      provider: "fabric8"
      project: "zipkin-mysql"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin-mysql-initdb"
  data:
    init.sql: "CREATE TABLE IF NOT EXISTS zipkin_spans (\n  `trace_id` BIGINT NOT\
      \ NULL,\n  `id` BIGINT NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `parent_id`\
      \ BIGINT,\n  `debug` BIT(1),\n  `start_ts` BIGINT COMMENT 'Span.timestamp():\
      \ epoch micros used for endTs query and to implement TTL',\n  `duration` BIGINT\
      \ COMMENT 'Span.duration(): micros used for minDuration and maxDuration query'\n\
      ) ENGINE=InnoDB ROW_FORMAT=COMPRESSED;\n\nALTER TABLE zipkin_spans ADD UNIQUE\
      \ KEY(`trace_id`, `id`) COMMENT 'ignore insert on duplicate';\nALTER TABLE zipkin_spans\
      \ ADD INDEX(`trace_id`, `id`) COMMENT 'for joining with zipkin_annotations';\n\
      ALTER TABLE zipkin_spans ADD INDEX(`trace_id`) COMMENT 'for getTracesByIds';\n\
      ALTER TABLE zipkin_spans ADD INDEX(`name`) COMMENT 'for getTraces and getSpanNames';\n\
      ALTER TABLE zipkin_spans ADD INDEX(`start_ts`) COMMENT 'for getTraces ordering\
      \ and range';\n\nCREATE TABLE IF NOT EXISTS zipkin_annotations (\n  `trace_id`\
      \ BIGINT NOT NULL COMMENT 'coincides with zipkin_spans.trace_id',\n  `span_id`\
      \ BIGINT NOT NULL COMMENT 'coincides with zipkin_spans.id',\n  `a_key` VARCHAR(255)\
      \ NOT NULL COMMENT 'BinaryAnnotation.key or Annotation.value if type == -1',\n\
      \  `a_value` BLOB COMMENT 'BinaryAnnotation.value(), which must be smaller than\
      \ 64KB',\n  `a_type` INT NOT NULL COMMENT 'BinaryAnnotation.type() or -1 if\
      \ Annotation',\n  `a_timestamp` BIGINT COMMENT 'Used to implement TTL; Annotation.timestamp\
      \ or zipkin_spans.timestamp',\n  `endpoint_ipv4` INT COMMENT 'Null when Binary/Annotation.endpoint\
      \ is null',\n  `endpoint_ipv6` BINARY(16) COMMENT 'Null when Binary/Annotation.endpoint\
      \ is null, or no IPv6 address',\n  `endpoint_port` SMALLINT COMMENT 'Null when\
      \ Binary/Annotation.endpoint is null',\n  `endpoint_service_name` VARCHAR(255)\
      \ COMMENT 'Null when Binary/Annotation.endpoint is null'\n) ENGINE=InnoDB ROW_FORMAT=COMPRESSED;\n\
      \nALTER TABLE zipkin_annotations ADD UNIQUE KEY(`trace_id`, `span_id`, `a_key`,\
      \ `a_timestamp`) COMMENT 'Ignore insert on duplicate';\nALTER TABLE zipkin_annotations\
      \ ADD INDEX(`trace_id`, `span_id`) COMMENT 'for joining with zipkin_spans';\n\
      ALTER TABLE zipkin_annotations ADD INDEX(`trace_id`) COMMENT 'for getTraces/ByIds';\n\
      ALTER TABLE zipkin_annotations ADD INDEX(`endpoint_service_name`) COMMENT 'for\
      \ getTraces and getServiceNames';\nALTER TABLE zipkin_annotations ADD INDEX(`a_type`)\
      \ COMMENT 'for getTraces';\nALTER TABLE zipkin_annotations ADD INDEX(`a_key`)\
      \ COMMENT 'for getTraces';\n\nCREATE TABLE IF NOT EXISTS zipkin_dependencies\
      \ (\n  `day` DATE NOT NULL,\n  `parent` VARCHAR(255) NOT NULL,\n  `child` VARCHAR(255)\
      \ NOT NULL,\n  `call_count` BIGINT\n) ENGINE=InnoDB ROW_FORMAT=COMPRESSED;\n\
      \nALTER TABLE zipkin_dependencies ADD UNIQUE KEY(`day`, `parent`, `child`);\n\
      GRANT SELECT, INSERT, UPDATE, DELETE ON zipkin.* TO zipkin@'%' IDENTIFIED BY\
      \ 'zipkin' WITH GRANT OPTION ;\nFLUSH PRIVILEGES;\n"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/git-branch: "release-v0.1.5"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
      fabric8.io/build-id: "3"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
    labels:
      provider: "fabric8"
      project: "zipkin"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin"
  spec:
    replicas: 1
    selector:
      provider: "fabric8"
      project: "zipkin"
      group: "io.fabric8.zipkin"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
          fabric8.io/build-id: "3"
          fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
          fabric8.io/git-branch: "release-v0.1.5"
          fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
        labels:
          provider: "fabric8"
          project: "zipkin"
          version: "0.1.5"
          group: "io.fabric8.zipkin"
      spec:
        containers:
        - env:
          - name: "STORAGE_PORT_9042_TCP_ADDR"
            value: "zipkin-cassandra:9411"
          - name: "STORAGE_PORT_3306_TCP_ADDR"
            value: "zipkin-mysql:3306"
          - name: "STORAGE_TYPE"
            value: "mysql"
          - name: "TRANSPORT_TYPE"
            value: "http"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "openzipkin/zipkin:1.13.0"
          name: "zipkin"
          readinessProbe:
            httpGet:
              path: "/api/v1/services"
              port: 9411
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
    triggers:
    - type: "ConfigChange"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/git-branch: "release-v0.1.5"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin-mysql&var-version=0.1.5"
      fabric8.io/build-id: "3"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
    labels:
      provider: "fabric8"
      project: "zipkin-mysql"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin-mysql"
  spec:
    replicas: 1
    selector:
      provider: "fabric8"
      project: "zipkin-mysql"
      group: "io.fabric8.zipkin"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin-mysql&var-version=0.1.5"
          fabric8.io/build-id: "3"
          fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
          fabric8.io/git-branch: "release-v0.1.5"
          fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
        labels:
          provider: "fabric8"
          project: "zipkin-mysql"
          version: "0.1.5"
          group: "io.fabric8.zipkin"
      spec:
        containers:
        - env:
          - name: "MYSQL_USER"
            value: "zipkin"
          - name: "MYSQL_PASSWORD"
            value: "zipkin"
          - name: "MYSQL_ROOT_PASSWORD"
            value: "zipkin"
          - name: "MYSQL_DATABASE"
            value: "zipkin"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "mysql:5.7"
          name: "zipkin-mysql"
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 3306
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: "mysql-data"
          - mountPath: "/docker-entrypoint-initdb.d/"
            name: "mysql-init-script"
          - mountPath: "/etc/mysql/conf.d/"
            name: "mysql-confd"
        volumes:
        - name: "mysql-data"
          hostPath:
            path: /pkar/data
        - configMap:
            name: "zipkin-mysql-initdb"
          name: "mysql-init-script"
        - configMap:
            name: "zipkin-mysql-cnf"
          name: "mysql-confd"
    triggers:
    - type: "ConfigChange"
```
but problem is mysql container not coming up.
error coming 
```
[root@ose-master Zipkin]# oc logs po/zipkin-mysql-2-deploy
--> Scaling zipkin-mysql-2 to 1
error: couldn't scale zipkin-mysql-2 to 1: timed out waiting for "zipkin-mysql-2" to be synced
```

oc describe command out put 

```
[root@ose-master Zipkin]# oc describe po/zipkin-mysql-2-deploy
Name:                   zipkin-mysql-2-deploy
Namespace:              default
Security Policy:        restricted
Node:                   10.20.30.28/10.20.30.28
Start Time:             Tue, 11 Jul 2017 06:24:41 -0400
Labels:                 openshift.io/deployer-pod-for.name=zipkin-mysql-2
Status:                 Failed
IP:                     10.1.3.5
Controllers:            <none>
Containers:
  deployment:
    Container ID:       docker://53e8826b5b6b061e1f400e61488d5059a8c81d3f9b15ce011ab26a94800e912c
    Image:              openshift3/ose-deployer:v3.3.0.32
    Image ID:           docker://sha256:0c6e9439e5e2c3374519c0ac7d595b372e1987b6cf0b3b1cd7d65fe312998ecf
    Port:
    State:              Terminated
      Reason:           Error
      Exit Code:        1
      Started:          Tue, 11 Jul 2017 06:24:44 -0400
      Finished:         Tue, 11 Jul 2017 06:26:46 -0400
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from deployer-token-rjqu0 (ro)
    Environment Variables:
      KUBERNETES_MASTER:        https://10.20.30.27:8443
      OPENSHIFT_MASTER:         https://10.20.30.27:8443
      BEARER_TOKEN_FILE:        /var/run/secrets/kubernetes.io/serviceaccount/token
      OPENSHIFT_CA_DATA:        -----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE0OTg4MTc5OTYwHhcNMTcwNjMwMTAxOTU1WhcNMjIwNjI5
MTAxOTU2WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE0OTg4MTc5OTYw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDOPQwsa6Lyj2t5FmuxSWbf
bYYmN/dHCul/xb9MAZyApBbq6us5z0FWJCG4qwiMbAcAG42d05WD2Y31Gkak9396
6iJ3Y0pErSlcxWopZC6lMAmW1Yz1RP0ml9DaMYxVO5TssT0MeCaehlajBZxcP7mu
UanZEpRaTwhcwKMHSmGI/M50iY2RV20A/0vWsxNKhJjA2wRnoMv6RoCYFgvhR96B
QpYBXYJMlXg5bHYLpqPKSxk8ECQQo4VjdxAP9Br6NTBtYpNUGmr/xKRe+jATrXQV
tL+ZlD0Ro/3NYdh92a1/ZUJKBfpdaZHuHEwe1ZZTCA2pEIN1HVFtAr+xVTNmbS1z
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQCchmcU0mh6Rekt6auQLQVl4KcKdLBcN5LppUSnGqlU+iz0
QpRok9hzD0/Qm4WaaX1oNVnI5u2hF2QE7oAQ6Z4sHFRMkaVLtysM7scMMq9o/WNK
evQk+HB78tF3MH+KmgswFnWPlpEH92tEzwT8XAcCbdPg8Pm5hZ6feli8YuHbqFGU
UvGD5TWIE3JtyP8lM7N255c0qlL/QpRLsvzcq29EdtZqa5uDefKvG2wg9/Syik2e
T1Q7lgF+YA8d/AwQIpAXP6oBYeFixHasJz5ialIHxYvvh90Fd4RAFxcWvAAFFUzJ
r8xXp/DS9jG9eAbywxkmn1INyLAkbul8O25LxjNy
-----END CERTIFICATE-----

      OPENSHIFT_DEPLOYMENT_NAME:        zipkin-mysql-2
      OPENSHIFT_DEPLOYMENT_NAMESPACE:   default
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  deployer-token-rjqu0:
    Type:       Secret (a volume populated by a Secret)
    SecretName: deployer-token-rjqu0
QoS Tier:       BestEffort
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                    -------------                   --------        ------          -------
  13m           13m             1       {default-scheduler }                                    Normal          Scheduled       Successfully assigned zipkin-mysql-2-deploy to 10.20.30.28
  13m           13m             1       {kubelet 10.20.30.28}   spec.containers{deployment}     Normal          Pulled          Container image "openshift3/ose-deployer:v3.3.0.32" already present on machine
  13m           13m             1       {kubelet 10.20.30.28}   spec.containers{deployment}     Normal          Created         Created container with docker id 53e8826b5b6b
  13m           13m             1       {kubelet 10.20.30.28}   spec.containers{deployment}     Normal          Started         Started container with docker id 53e8826b5b6b
[root@ose-master Zipkin]#
```
